// File generated by FlutterFire CLI.
// This file must be replaced with actual Firebase configuration
// after creating a Firebase project.
//
// To generate this file, run:
//   flutterfire configure
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace these placeholder values with your actual
/// Firebase project configuration from the Firebase console.
///
/// To get your configuration:
/// 1. Go to https://console.firebase.google.com
/// 2. Create a new project or select existing one
/// 3. Add Android and iOS apps
/// 4. Download configuration files or run `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9u9jrVkY9OXslo3LqPiOfLVA_eRKOboc',
    appId: '1:469138142638:android:725ed41af26fb605dec43f',
    messagingSenderId: '469138142638',
    projectId: 'famille-tree',
    storageBucket: 'famille-tree.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9u9jrVkY9OXslo3LqPiOfLVA_eRKOboc',
    appId: '1:469138142638:web:3cbcd8fdded6a0dddec43f',
    messagingSenderId: '469138142638',
    projectId: 'famille-tree',
    authDomain: 'famille-tree.firebaseapp.com',
    storageBucket: 'famille-tree.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQb4f3E6K0ulbNUqLTa6e8ksh6Lbqqd0',
    appId: '1:469138142638:ios:df73784ed0030221dec43f',
    messagingSenderId: '469138142638',
    projectId: 'famille-tree',
    storageBucket: 'famille-tree.firebasestorage.app',
    iosClientId:
        '469138142638-ios-client-id-placeholder.apps.googleusercontent.com', // Will update if found in plist
    iosBundleId: 'com.famille.familleTree',
  );
}
